### ISSUE TITLE
Whether the pre-trained model is the model of the results in the paper

### ISSUE THREAD

**Issue by ligungun** [MengHao666/HDR#10]
Whether the pre-trained model is the model of the results in the paper

Thank you for open sourcing the code, it's a really interesting job.

Thanks for open sourcing Google Drive pretrained models.

Does this pre-training model correspond to the experimental results in the paper? Or just a demo model, not the SOTA model in the paper?

Thanks!

**Comment by MengHao666** [comment]
> 

It is just a demo model. As I could remember, this is only the model that is named as "IH26M-SH" of "InterHand2.6M-Mbranch" in the Table1 of the paper.

**Comment by ligungun** [comment]
> It is just a demo model. As I could remember, this is only the model that is named as "IH26M-SH" of "InterHand2.6M-Mbranch" in the Table1 of the paper.

Thanks for your reply, 
is the Interhand_seg/iter_237500.pth model trained on all datasets? Or just train on a dataset with machine annotations. Thanks。

**Comment by MengHao666** [comment]
> 
the provided segmentation model is trained on whole available "IH" ( named in the InterHand2.6M paper) data, consisting of machine_annot and human_annot.

**Comment by ligungun** [comment]
> 
Thank you very much for your reply
