### ISSUE TITLE
problem about 'load checkpoint false'

### ISSUE THREAD

**Issue by wenkaiH** [MengHao666/HDR#11]
![QQ图片20230530160133](https://github.com/MengHao666/HDR/assets/130635073/a6b4ee52-3d91-45c4-831a-a77ca8e9591d)

**Comment by MengHao666** [comment]
I did not meet such question. Is it possible due to library version or path-related problem ?

**Comment by wenkaiH** [comment]
> I did not meet such question. Is it possible due to library version or path-related problem ?

I also think so. I will remove the sys path and replace it with an absolute path. successful!

**Comment by dashuaizeng** [comment]
> > I did not meet such question. Is it possible due to library version or path-related problem ?
> 
> I also think so. I will remove the sys path and replace it with an absolute path. successful!

Hello, may I ask what work needs to be done before configuring the. yml file
