### ISSUE TITLE
demo_work_dirs file missing

### ISSUE THREAD

**Issue by dashuaizeng** [MengHao666/HDR#13]
OSError： ./dome_work_dirs/Interhand_seg/iter_237500.pth is not a checkpoint file

**Comment by MengHao666** [comment]
please check if you have download the checkpoint file mentioned in readme. And you could use absolute path if you have got the model

**Comment by dashuaizeng** [comment]
Thank you very much for your reply. Could you check the file for me in the form of Baidu Wangpan? Thanks again.

**Comment by dashuaizeng** [comment]
> please check if you have download the checkpoint file mentioned in readme. And you could use absolute path if you have got the model

thanks，i do.
