### ISSUE TITLE
On the issue of poor performance in replacing test images

### ISSUE THREAD

**Issue by dashuaizeng** [MengHao666/HDR#14]
I am replacing Tzionas_ Dataset-02-1-rgb-100.png took a picture of my own crossed hands, but the effect was not good after running. May I ask if it is related to Tzionas_ Dataset-02-1-joints_ 2D_ Is GT-100.txt related to this file? Please provide guidance.

**Comment by MengHao666** [comment]
I provide the related data here. Please note I did not have copyright of original data. And indeed poor performance does occur when the sample is unseen in training data. 
LINK：https://pan.baidu.com/s/1UHw---dF-trEx7gMq8uOgw 
CODE：kxan

**Comment by dashuaizeng** [comment]
Okay, thank you very much. I will study the document you provided

**Comment by dashuaizeng** [comment]
Tzionas_ Dataset-02-1-joints_ 2D_ Is GT-100.txt，How are these types of files generated? What does it mean?

**Comment by dashuaizeng** [comment]
> I provide the related data here. Please note I did not have copyright of original data. And indeed poor performance does occur when the sample is unseen in training data. LINK：https://pan.baidu.com/s/1UHw---dF-trEx7gMq8uOgw CODE：kxan

Tzionas_ Dataset-02-1-joints_ 2D_ Is GT-100.txt，How are these types of files generated? What does it mean?

**Comment by MengHao666** [comment]
It is the predicted 2D hand pose generated by "HPE" model mentioned in paper.

**Comment by dashuaizeng** [comment]
> It is the predicted 2D hand pose generated by "HPE" model mentioned in paper.

There should be 21 joint points for Gesture recognition. Why are there 28 lines of data? Please advise

**Comment by MengHao666** [comment]
> > It is the predicted 2D hand pose generated by "HPE" model mentioned in paper.
> 
> There should be 21 joint points for Gesture recognition. Why are there 28 lines of data? Please advise

I am afraid I forget something. It could be the joint configuration of Tzionas Dataset. I suggest you check the original Tzionas dataset.

**Comment by dashuaizeng** [comment]
> > > It is the predicted 2D hand pose generated by "HPE" model mentioned in paper.
> > 
> > 
> > There should be 21 joint points for Gesture recognition. Why are there 28 lines of data? Please advise
> 
> I am afraid I forget something. It could be the joint configuration of Tzionas Dataset. I suggest you check the original Tzionas dataset.

Thank you. Let me check it out

**Comment by dashuaizeng** [comment]
> > > It is the predicted 2D hand pose generated by "HPE" model mentioned in paper.
> > 
> > 
> > There should be 21 joint points for Gesture recognition. Why are there 28 lines of data? Please advise
> 
> I am afraid I forget something. It could be the joint configuration of Tzionas Dataset. I suggest you check the original Tzionas dataset.

Can you provide some insights or guidance files for the Tzionas dataset, i.e.. TXT files

**Comment by MengHao666** [comment]
I am sorry I could not rememeber so much details. You could find that I first try to localize the hand position to crop the image, and then do hand de-occlusion and removal. If there is no 2D joint for easy localization in Tzionas Dataset, then it might be that I try to get 2D joint pose with hand pose estimation module.

**Comment by dashuaizeng** [comment]
> I am sorry I could not rememeber so much details. You could find that I first try to localize the hand position to crop the image, and then do hand de-occlusion and removal. If there is no 2D joint for easy localization in Tzionas Dataset, then it might be that I try to get 2D joint pose with hand pose estimation module.

Okay, I'll try my best to understand. Thank you for your reply
