### ISSUE TITLE
How to get the 2D GT for hand when I run demo.py on my own image?

### ISSUE THREAD

**Issue by Xianjin111** [MengHao666/HDR#5]
Thank you for your perfect work. I would like to test on my own image, so how could I get the 2D GT (.txt) for my own image?

Thx~

**Comment by MengHao666** [comment]
> Thank you for your perfect work. I would like to test on my own image, so how could I get the 2D GT (.txt) for my own image?
> 
> Thx~

Note the 2d joint gt here is for roughly localizing the two closely interacting hands. In my paper, 2d joint gt could be obtained by the academic dataset itself. For wild settings, you may need to get a detector to get the coarse position of interactive hand. Our HDR model is currently only trained on Inerhand v1.0 dataset, so it could only fit to similar situation in the wild.

**Comment by Xianjin111** [comment]
> 

Got it. Thank you very much.
