### ISSUE TITLE
About demo file

### ISSUE THREAD

**Issue by redorangeyellowy** [MengHao666/HDR#6]
Thank you for your interesting research.

I implemented the demo file you provided about the interhand 2.6m dataset, and the result was not good as below.

![image](https://user-images.githubusercontent.com/86509883/200552936-9c6f2aa4-46be-4e9a-8cad-2fb73eb4d957.png)
![image](https://user-images.githubusercontent.com/86509883/200553028-3e14f420-33f0-42a7-8939-9b9e68255c5c.png)

I wonder if you can tell me the path of the image to see the result well when I put in the image.

**Comment by MengHao666** [comment]
Such failure does exists. You may go through the whole dataset to find similar sample like which showed in the paper. Further research might introduce semantic information as fine-grained constraints to further improve results

**Comment by redorangeyellowy** [comment]
Okay. Thank you for your reply.
